conf_mapping = {
    'Boston College': "ACC",
    'California': "ACC",
    'Clemson': "ACC",
    'Duke': "ACC",
    'Florida State': "ACC",
    'Georgia Tech': "ACC",
    'Miami': "ACC",
    'NC State': "ACC",
    'North Carolina': "ACC",
    'Pittsburgh': "ACC",
    'SMU': "ACC",
    'Stanford': "ACC",
    'Syracuse': "ACC",
    'Virginia': "ACC",
    'Virginia Tech': "ACC",
    'Wake Forest': "ACC",
    'Louisville': "ACC",
    'Alabama': "SEC",
    'Arkansas': "SEC",
    'Auburn': "SEC",
    'Florida': "SEC",
    'Georgia': "SEC",
    'Kentucky': "SEC",
    'LSU': "SEC",
    'Mississippi State': "SEC",
    'Missouri': "SEC",
    'Oklahoma': "SEC",
    'Ole Miss': "SEC",
    'South Carolina': "SEC",
    'Tennessee': "SEC",
    'Texas': "SEC",
    'Texas A&M': "SEC",
    'Vanderbilt': "SEC",
    'Illinois':"Big10",
    'Indiana':"Big10",
    'Iowa':"Big10",
    'Maryland':"Big10",
    'Michigan':"Big10",
    'Michigan State':"Big10",
    'Minnesota':"Big10",
    'Nebraska':"Big10",
    'Northwestern':"Big10",
    'Ohio State':"Big10",
    'Oregon':"Big10",
    'Penn State':"Big10",
    'Purdue':"Big10",
    'Rutgers':"Big10",
    'UCLA':"Big10",
    'USC':"Big10",
    'Washington':"Big10",
    'Wisconsin':"Big10",
    'Arizona':"Big12",
    'Arizona State':"Big12",
    'BYU':"Big12",
    'Baylor':"Big12",
    'Cincinnati':"Big12",
    'Colorado':"Big12",
    'Houston':"Big12",
    'Iowa State':"Big12",
    'Kansas':"Big12",
    'Kansas State':"Big12",
    'TCU':"Big12",
    'Texas Tech':"Big12",
    'UCF':"Big12",
    'Utah':"Big12",
    'West Virginia':"Big12",
    'Oklahoma State':"Big12",
    'Air Force':"MWC",
    'Boise State':"MWC",
    'Colorado State':"MWC",
    'Fresno State':"MWC",
    "Hawai'i":"MWC",
    'Wyoming':"MWC",
    'UNLV':"MWC",
    'Utah State':"MWC",
    'San Diego State':"MWC",
    'New Mexico':"MWC",
    'San José State':"MWC",
    'Nevada':"MWC",
    'Army':"American",
    'UAB':"American",
    'Florida Atlantic':"American",
    'East Carolina':"American",
    'Charlotte':"American",
    'Memphis':"American",
    'Navy':"American",
    'North Texas':"American",
    'Rice':"American",
    'Temple':"American",
    'Tulane':"American",
    'Tulsa':"American",
    'South Florida':"American",
    'UTSA':"American",
    'Florida International':"CUSA",
    'Jacksonville State':"CUSA",
    'Kennesaw State':"CUSA",
    'Liberty':"CUSA",
    'Louisiana Tech':"CUSA",
    'Middle Tennessee':"CUSA",
    'New Mexico State':"CUSA",
    'Sam Houston':"CUSA",
    'Western Kentucky':"CUSA",
    'UTEP':"CUSA",
    'Akron':"MAC",
    'Ball State':"MAC",
    'Bowling Green':"MAC",
    'Buffalo':"MAC",
    'Central Michigan':"MAC",
    'Eastern Michigan':"MAC",
    'Kent State':"MAC",
    'Miami (OH)':"MAC",
    'Northern Illinois':"MAC",
    'Ohio':"MAC",
    'Toledo':"MAC",
    'Western Michigan':"MAC",
    'App State':"SunBelt",
    'Coastal Carolina':"SunBelt",
    'Georgia Southern':"SunBelt",
    'Georgia State':"SunBelt",
    'James Madison':"SunBelt",
    'Marshall':"SunBelt",
    'Old Dominion':"SunBelt",
    'Arkansas State':"SunBelt",
    'UL Monroe':"SunBelt",
    'Lafayette':"SunBelt",
    'Southern Miss':"SunBelt",
    'South Alabama':"SunBelt",
    'Texas State':"SunBelt",
    'Troy':"SunBelt",
    'Louisiana':"SunBelt",
    'Notre Dame':"FBSI",
    'Oregon State':"FBSI",
    'Washington State':"FBSI",
    'UConn':"FBSI",
    'Massachusetts':"FBSI",

    'Eastern Washington':"BigSky",
    'Idaho':"BigSky",
    'Idaho State':"BigSky",
    'Montana':"BigSky",
    'Montana State':"BigSky",
    'Northern Arizona':"BigSky",
    'Northern Colorado':"BigSky",
    'Portland State':"BigSky",
    'Sacramento State':"BigSky",
    'Weber State':"BigSky",
    'UC Davis':"BigSky",
    'Cal Poly':"BigSky",
    'Illinois State':"MVFC",
    'Indiana State':"MVFC",
    'Missouri State':"MVFC",
    'Murray State':"MVFC",
    'North Dakota':"MVFC",
    'North Dakota State':"MVFC",
    'Northern Iowa':"MVFC",
    'South Dakota':"MVFC",
    'South Dakota State':"MVFC",
    'Southern Illinois':"MVFC",
    'Youngstown State:"MVFC"'
    'Alabama A&M':"SWAC",
    'Alabama State':"SWAC",
    'Bethune-Cookman':"SWAC",
    'Florida A&M':"SWAC",
    'Jackson State':"SWAC",
    'Mississippi Valley State':"SWAC",
    'Alcorn State':"SWAC",
    'Arkansas-Pine Bluff':"SWAC",
    'Grambling':"SWAC",
    'Prairie View A&M':"SWAC",
    'Southern':"SWAC",
    'Texas Southern':"SWAC",
    'Delaware State':"MEAC",
    'Howard':"MEAC",
    'Morgan State':"MEAC",
    'Norfolk State':"MEAC",
    'North Carolina Central':"MEAC",
    'South Carolina State':"MEAC",
    'Brown':"Ivy",
    'Columbia':"Ivy",
    'Cornell':"Ivy",
    'Dartmouth':"Ivy",
    'Pennsylvania':"Ivy",
    'Yale':"Ivy",
    'Harvard':"Ivy",
    'Princeton':"Ivy",
    'Charleston Southern':"Big_South",
    'Gardner-Webb':"Big_South",
    'Southeast Missouri State':"Big_South",
    'Tennessee Tech':"Big_South",
    'UT Martin':"Big_South",
    'Tennessee State':"Big_South",
    'Lindenwood':"Big_South",
    'Western Illinois':"Big_South",
    'Eastern Illinois':"Big_South",
    'Campbell':"Coastal",
    'Delaware':"Coastal",
    'Elon':"Coastal",
    'Hampton':"Coastal",
    'Monmouth':"Coastal",
    'North Carolina A&T':"Coastal",
    'Stony Brook':"Coastal",
    'Towson':"Coastal",
    'William & Mary':"Coastal",
    'Rhode Island':"Coastal",
    'Richmond':"Coastal",
    'Villanova':"Coastal",
    'New Hampshire':"Coastal",
    'Maine':"Coastal",
    'UAlbany':"Coastal",
    'Bryant':"Coastal",
    'Central Connecticut':"Northeast",
    'Duquesne':"Northeast",
    'Long Island University':"Northeast",
    'Robert Morris':"Northeast",
    'St. Francis (PA)':"Northeast",
    'Stonehill':"Northeast",
    'Mercyhurst':"Northeast",
    'Wagner':"Northeast",
    'Lehigh':"Patriot",
    'Holy Cross':"Patriot",
    'Bucknell':"Patriot",
    'Fordham':"Patriot",
    'Colgate':"Patriot",
    'Georgetown':"Patriot",
    'Lafayette':"Patriot",
    'Drake':"Pioneer",
    'Davidson':"Pioneer",
    'Dayton':"Pioneer",
    'Butler':"Pioneer",
    'San Diego':"Pioneer",
    'Morehead State':"Pioneer",
    'St. Thomas-Minnesota':"Pioneer",
    'Valparaiso':"Pioneer",
    'Presbyterian':"Pioneer",
    'Stetson':"Pioneer",
    'Marist':"Pioneer",
    'Mercer':"Southern",
    'Western Carolina':"Southern",
    'Chattanooga':"Southern",
    'East Tennessee State':"Southern",
    'Samford':"Southern",
    'The Citadel':"Southern",
    'Wofford':"Southern",
    'VMI':"Southern",
    'Furman':"Southern",
    'Nicholls':"Southland",
    'Northwestern State':"Southland",
    'McNeese':"Southland",
    'East Texas A&M':"Southland",
    'Lamar':"Southland",
    'Houston Christian':"Southland",
    'Stephen F. Austin':"Southland",
    'SE Louisiana':"Southland",
    'Incarnate Word':"Southland",
    'Abilene Christian':"United",
    'Eastern Kentucky':"United",
    'Southern Utah':"United",
    'Tarleton State':"United",
    'Austin Peay':"United",
    'Central Arkansas':"United",
    'North Alabama':"United",
    'Utah Tech':"United",
    'West Georgia':"United",
    'Merrimack':"FCSI",
}

conf_levels = {
    'ACC':'FBS',
    'SEC':'FBS',
    'Big10':'FBS',
    'Big12':'FBS',
    'MWC':'FBS',
    'American':'FBS',
    'CUSA':'FBS',
    'MAC':'FBS',
    'SunBelt':'FBS',
    'FBSI':'FBS',
    'BigSky':'FCS',
    'MVFC':'FCS',
    'SWAC':'FCS',
    'MEAC':'FCS',
    'Ivy':'FCS',
    'Big_South':'FCS',
    'Coastal':'FCS',
    'Northeast':'FCS',
    'Patriot':'FCS',
    'Pioneer':'FCS',
    'Southern':'FCS',
    'Southland':'FCS',
    'United':'FCS',
    'FCSI':'FCS',
}